language: c
compiler:
  - gcc
  - clang

before_script:
  - wget http://releases.linaro.org/14.05/components/toolchain/binaries/gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux.tar.xz
  - tar xvf gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux.tar.xz
  - xport PATH=$PATH/toolchains/gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux/bin:$PATH

script:
  - make
  - CFG_TEE_CLIENT_LOG_LEVEL=5 make
