language: c
#compiler:
#  - gcc
#  - clang

notifications:
  - email: true

#before_script:
#  - wget http://releases.linaro.org/14.05/components/toolchain/binaries/gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux.tar.xz
#  - tar xvf gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux.tar.xz
#  - export PATH=$PWD/gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux/bin:$PATH
#  - echo $PATH
#  - arm-linux-gnueabihf-gcc -v

before_install:
  - wget http://releases.linaro.org/14.05/components/toolchain/binaries/gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux.tar.xz
  - tar xvf gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux.tar.xz
  - export PATH=$PATH:$PWD/gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux/bin

script:
  - uname -a
  - echo $PATH
  - ls -al $PWD/gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux/bin/arm-linux-gnueabihf-gcc
  - ls -al $PWD/gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux/bin/arm-linux-gnueabihf-gcc-4.9.1
  - /home/travis/build/pascal-brand-st-dev/optee_client/gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux/bin/arm-linux-gnueabihf-gcc-4.9.1 -v
  - arm-linux-gnueabihf-gcc-4.9.1 -v
  - arm-linux-gnueabihf-gcc -v
  - ls -al $PWD/gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux/bin/arm-linux-gnueabihf-gcc
  - ls -al $PWD/gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux/bin/arm-linux-gnueabihf-gcc-4.9.1
  - rm $PWD/gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux/bin/arm-linux-gnueabihf-gcc
  - cp $PWD/gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux/bin/arm-linux-gnueabihf-gcc-4.9.1 $PWD/gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux/bin/arm-linux-gnueabihf-gcc
  - arm-linux-gnueabihf-gcc-4.9.1 -v
  - arm-linux-gnueabihf-gcc -v
  - make
  - CFG_TEE_CLIENT_LOG_LEVEL=5 make
