# One may have a look at http://docs.travis-ci.com/user/installing-dependencies/

# language: c
#compiler:
#  - gcc
#  - clang

notifications:
  - email: true

#before_script:
#  - wget http://releases.linaro.org/14.05/components/toolchain/binaries/gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux.tar.xz
#  - tar xvf gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux.tar.xz
#  - export PATH=$PWD/gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux/bin:$PATH
#  - echo $PATH
#  - arm-linux-gnueabihf-gcc -v

before_install:
  - sudo apt-get install ia32-libs -y


before_script:
  # - wget http://releases.linaro.org/14.05/components/toolchain/binaries/gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux.tar.xz
  # - tar xvf gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux.tar.xz
  # - export PATH=$PATH:$PWD/gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux/bin
  - wget http://releases.linaro.org/12.05/components/toolchain/binaries/gcc-linaro-arm-linux-gnueabihf-2012.05-20120523_linux.tar.bz2
  - bunzip2 gcc-linaro-arm-linux-gnueabihf-2012.05-20120523_linux.tar.bz2
  - tar xvf gcc-linaro-arm-linux-gnueabihf-2012.05-20120523_linux.tar
  - export PATH=$PATH:$PWD/gcc-linaro-arm-linux-gnueabihf-2012.05-20120523_linux/bin

script:
  - uname -a
  - echo $PATH
  - ls -al $PWD/gcc-linaro-arm-linux-gnueabihf-2012.05-20120523_linux/bin/arm-linux-gnueabihf-gcc
  - /home/travis/build/pascal-brand-st-dev/optee_client/gcc-linaro-arm-linux-gnueabihf-2012.05-20120523_linux/bin/arm-linux-gnueabihf-gcc -v
  - PATH=$PATH:$PWD/gcc-linaro-arm-linux-gnueabihf-2012.05-20120523_linux/bin arm-linux-gnueabihf-gcc -v
  - PATH=$PATH:$PWD/gcc-linaro-arm-linux-gnueabihf-2012.05-20120523_linux/bin make
  - CFG_TEE_CLIENT_LOG_LEVEL=5 make
